blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/EarthlingsMusicGroup/EMG-NFT-Metadata-Builder/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/EarthlingsMusicGroup/EMG-NFT-Metadata-Builder/tree/main/docs
    about: Check the documentation for answers

