blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/BankkRoll/nft-metadata-builder/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/BankkRoll/nft-metadata-builder/tree/main/docs
    about: Check the documentation for answers

